name: Integration test
on:
  push:
    branches:
      - test/**

jobs:
  firebase_test_lab:
    runs-on: macos-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
          architecture: x64

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISIONING_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Pub get
        run: make clean && make get

      - name: Set up gcloud sdk
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Check gcloud info
        run: gcloud info
      
      - name: Check xcode info
        run: xcodebuild -version
        run: xcodebuild -showsdks

      - name: authenticate gcloud sdk
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GA }}

      # - name: Run integration testing on Android
      #   run: ./android_integration.sh

      # - name: Setup XCode SDK version
      #   uses: sinoru/actions-setup-xcode@v2
      #   with:
      #     xcode-version: '14.7'

      - name: Run integration testing on iOS
        run: ./ios_integration.sh

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision

  # integration_test_ios:
  #   runs-on: macos-latest
  #   strategy:
  #     fail-fast: true
  #   steps:
  #     - name: Setup repository
  #       uses: actions/checkout@v2

  #     - name: Setup Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'

  #     - name: Setup Flutter SDK
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.0.5'
  #         channel: 'stable'
  #         architecture: x64

  #     - name: Pub get
  #       run: make clean && make get

  #     - name: Run integration test on ios
  #       uses: futureware-tech/simulator-action@v1
  #       with:
  #         model: 'iPhone 8'
  #         os: 'iOS'
  #         os_version: ">=15"
  #         erase_before_boot: true
  #         shutdown_after_job: true
  #     - run: make do_test

  # integration_test_android:
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       android-api-level: [29]
  #       android-target: [playstore]
  #     fail-fast: true
  #   steps:
  #     - name: Setup repository
  #       uses: actions/checkout@v2

  #     - name: Setup Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'

  #     - name: Setup Flutter SDK
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.0.5'
  #         channel: 'stable'
  #         architecture: x64

  #     - name: Pub get
  #       run: make clean && make get

  #     - name: Run integration test on android
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         target: ${{ matrix.android-target }}
  #         api-level: ${{ matrix.android-api-level }}
  #         arch: x86_64
  #         profile: Nexus 6
  #         script: make do_test