name: Integration test
on:
  push:
    branches:
      - 'test/**'

jobs:
  integration_test_android:
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     api-level: [29]
    #     target: [playstore]
    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          architecture: x64

      - name: Pub get
        run: make clean && make get

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: [29]
          api-level: [playstore]
          arch: x86_64
          profile: Nexus 6
          # script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/increment_success_test.dart
          script: flutter test integration_test/login_test.dart -r expanded

      # Update screenshot to artifact
      # - name: Upload screenshots
      #   if: always()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: screenshot
      #     path: ${{ matrix.path }}screenshots/